[package]
name = "db-keystore"
version = "0.4.0"
edition = "2024"
authors = ["Steve Schoettler <stevelr-git@pm.me>"]
description = "SQLite-backed credential store for the `keyring-core` API"
repository = "https://github.com/stevelr/db-keystore"
homepage = "https://github.com/stevelr/db-keystore"
license = "MIT or Apache-2.0"
keywords = ["keyring", "credential", "sqlite", "turso", "secrets-manager"]
categories = ["database", "api-bindings"]
readme = "README.md"
rust-version = "1.88"

[lib]

[[bin]]
name = "db-keystore"
path = "bin/db-keystore.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.56", features = ["derive"] }
futures = "0.3.31"
keyring-core = "0.7.2"
log = "0.4.29"
regex = "1.12.3"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
turso = "0.4.4"
uuid = { version = "=1.20.0", features = ["v7"] }
zeroize = "1.8.1"

[dev-dependencies]
tempfile = "=3.24.0"
