[package]
name = "db-keystore"
version = "0.2.2"
edition = "2024"
authors = ["Steve Schoettler <stevelr-git@pm.me>"]
description = "SQLite-backed credential store for the `keyring-core` API"
repository = "https://github.com/stevelr/db-keystore"
homepage = "https://github.com/stevelr/db-keystore"
license = "MIT or Apache-2.0"
keywords = ["keyring", "credential", "sqlite", "turso", "secrets-manager"]
categories = ["database", "api-bindings"]
readme = "README.md"

[lib]

[[bin]]
name = "dump-db-keystore"
path = "bin/dump-db-keystore.rs"

[dependencies]
futures = "=0.3.31"
keyring-core = "=0.7.2"
regex = "=1.12.2"
turso = "0.4.3"
uuid = { version = "=1.19.0", features = ["v4"] }

[dev-dependencies]
tempfile = "=3.24.0"
